export const Users = [
  {
    id: "1",
    profilePicture: "https://i.pinimg.com/564x/de/16/a0/de16a0b61a93d8ee51618370ac52db86.jpg",
    username: "Takuya Kimura",
  },
  {
    id: "2",
    profilePicture: "https://upload.wikimedia.org/wikipedia/commons/e/e1/Matt_Damon_2014_3.jpg",
    username: "Matt Damon",
  },
  {
    id: "3",
    profilePicture: "https://www.biography.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:good%2Cw_1200/MTQyNjA5MzczMDc4NzU4NzI3/matthew-mcconaughey-gettyimages-589532902_1600jpg.jpg",
    username: "Matthew V McConaughey",
  },
  {
    id: "4",
    profilePicture: "https://i0.wp.com/abtc.ng/wp-content/uploads/2022/03/Benedict-Cumberbatch-Looper.jpg?resize=770%2C438&ssl=1",
    username: "Benedict Cumberbatch",
  },
  {
    id: "5",
    profilePicture: "https://www.hollywoodreporter.com/wp-content/uploads/2021/12/GettyImages-1208185780-h-2021.jpg",
    username: "Tom Holland",
  },
  {
    id: "6",
    profilePicture: "https://api.time.com/wp-content/uploads/2014/03/479748569.jpg",
    username: "Chris Evans",
  },
  {
    id: "7",
    profilePicture: "https://cdn.britannica.com/92/215392-050-96A4BC1D/Australian-actor-Chris-Hemsworth-2019.jpg",
    username: "Chris Hemsworth",
  },
  {
    id: "8",
    profilePicture: "https://www.pinkvilla.com/imageresize/tom_hiddleston_0.jpeg?width=752&format=webp&t=pvorg",
    username: "Tom Hiddleston",
  },
  {
    id: "9",
    profilePicture: "https://japantoday-asset.scdn3.secure.raxcdn.com/img/store/af/5a/3e015fe29c773cf3632ff8adf7d3bb6bbd9c/hunter/_w850.jpg",
    username: "Daimon Michiko",
  },
  {
    id: "10",
    profilePicture: "https://upload.wikimedia.org/wikipedia/commons/7/74/Erika_Toda_IMG_1134-1_20200203.jpg",
    username: "Erika Toda",
  },
];

export const Posts = [
  {
    id: "1",
    description: "Snow and forest ❄️",
    image: "https://images.pexels.com/photos/351448/pexels-photo-351448.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    date: "5 mins ago",
    userId: "1",
    likes: 32,
    comments: "9",
  },
  {
    id: "2",
    image: "https://i.ytimg.com/vi/Y0acgkhbvS0/maxresdefault.jpg",
    date: "15 mins ago",
    userId: "2",
    likes: 2,
    comments: "1",
  },
  {
    id: "3",
    description: "Seasons in the Sun! ☀️ Today marks the vernal equinox, or the #FirstDayofSpring in the Northern Hemisphere and first day of autumn in the Southern Hemisphere. Twice a year, on the equinoxes, both hemispheres will see equal amounts of daylight:",
    image: "https://pbs.twimg.com/media/FOUNbJfXIAQ-BX_?format=jpg&name=medium",
    date: "1 hour ago",
    userId: "3",
    likes: 61,
    comments: "2",
  },
  {
    id: "4",
    image: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: "4",
    likes: 7,
    comments: "3",
  },
  {
    id: "5",
    image: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: "5",
    likes: 23,
    comments: "5",
  },
  {
    id: "6",
    image: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: "6",
    likes: 44,
    comments: "6",
  },
  {
    id: "7",
    description: "Never regret anything that made you smile.",
    image: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: "7",
    likes: 52,
    comments: "3",
  },
  {
    id: "8",
    image: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: "8",
    likes: 15,
    comments: "1",
  },
  {
    id: "9",
    description: "Change the world by being yourself.",
    image: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: "9",
    likes: 11,
    comments: "2",
  },
  {
    id: "10",
    image: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: "10",
    likes: 104,
    comments: "12",
  },
];